version: "3"
services:
  oftien:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oftien
    ports:
      - 7080:2810
    entrypoint: ["sh", "-c"]
    command: ["yarn start"]
